---
version: "2"
services:
  webgrab:
    build:
      context: ./webgrab/
    image: psibo/webgrabplus
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    volumes:
      - ${PWD}/work/webgrab-config:/config
      - ${PWD}/work/output:/data
    restart: unless-stopped
    depends_on: ["nginx"]

  nginx:
    image: nginx:latest
    volumes:
      - ${PWD}/work/php:/code
      - ${PWD}/nginx/site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on: ["php"]
    
  php:
    build:
      context: ./php/
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
    image: psibo/php:7-fpm
    volumes:
      - ${PWD}/work/php:/var/www/html
    restart: unless-stopped
